#
# Makefile for IIO Health sensors
#

# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_AFE4403)		+= afe4403.o
obj-$(CONFIG_AFE4404)		+= afe4404.o
obj-$(CONFIG_AFE4410)		+= afe4410-core.o
obj-$(CONFIG_AFE4410_I2C)	+= afe4410-i2c.o
obj-$(CONFIG_AFE4410_SPI)	+= afe4410-spi.o
obj-$(CONFIG_MAX30100)		+= max30100.o
