#
# Makefile for IIO Health sensors
#

# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_AFE4403)		+= afe4403.o
obj-$(CONFIG_AFE4404)		+= afe4404.o
obj-$(CONFIG_AFE4420)		+= afe4420-core.o
obj-$(CONFIG_AFE4420_I2C)	+= afe4420-i2c.o
obj-$(CONFIG_AFE4420_SPI)	+= afe4420-spi.o
obj-$(CONFIG_MAX30100)		+= max30100.o
